version: "3"
services:
  flask:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
    volumes:
      - ./backend:/app
      - sqlite-data:/app/instance
volumes:
  sqlite-data:
